In [1]:
from gensim.models import KeyedVectors

In [6]:
import gensim
from urllib.request import urlretrieve, urlopen
import gzip
import zipfile

urlretrieve("http://nlp.stanford.edu/data/glove.6B.zip", filename="glove.6B.zip")

('glove.6B.zip', <http.client.HTTPMessage at 0x79f6289888e0>)

In [7]:
zf = zipfile.ZipFile('glove.6B.zip')
zf.extractall()
zf.close()

In [9]:
import numpy as np
embedding_dict = dict()

f = open('glove.6B.100d.txt', encoding="utf8")

for line in f:
    word_vector = line.split()
    word = word_vector[0]

    # 100개의 값을 가지는 array로 변환
    word_vector_arr = np.asarray(word_vector[1:], dtype='float32')
    embedding_dict[word] = word_vector_arr
f.close()

print('%s개의 Embedding vector가 있습니다.' % len(embedding_dict))

400000개의 Embedding vector가 있습니다.


In [23]:
print(embedding_dict['hello'])
print('벡터의 차원 수 :',len(embedding_dict['hello']))

[ 0.26688    0.39632    0.6169    -0.77451   -0.1039     0.26697
  0.2788     0.30992    0.0054685 -0.085256   0.73602   -0.098432
  0.5479    -0.030305   0.33479    0.14094   -0.0070003  0.32569
  0.22902    0.46557   -0.19531    0.37491   -0.7139    -0.51775
  0.77039    1.0881    -0.66011   -0.16234    0.9119     0.21046
  0.047494   1.0019     1.1133     0.70094   -0.08696    0.47571
  0.1636    -0.44469    0.4469    -0.93817    0.013101   0.085964
 -0.67456    0.49662   -0.037827  -0.11038   -0.28612    0.074606
 -0.31527   -0.093774  -0.57069    0.66865    0.45307   -0.34154
 -0.7166    -0.75273    0.075212   0.57903   -0.1191    -0.11379
 -0.10026    0.71341   -1.1574    -0.74026    0.40452    0.18023
  0.21449    0.37638    0.11239   -0.53639   -0.025092   0.31886
 -0.25013   -0.63283   -0.011843   1.377      0.86013    0.20476
 -0.36815   -0.68874    0.53512   -0.46556    0.27389    0.4118
 -0.854     -0.046288   0.11304   -0.27326    0.15636   -0.20334
  0.53586    0.59784   

In [25]:
import gensim.downloader
glove_vectors1 = gensim.downloader.load('glove-twitter-25')
glove_vectors1.most_similar('twitter')

[==================================================] 100.0% 104.8/104.8MB downloaded


[('facebook', 0.948005199432373),
 ('tweet', 0.9403423070907593),
 ('fb', 0.9342358708381653),
 ('instagram', 0.9104824066162109),
 ('chat', 0.8964964747428894),
 ('hashtag', 0.8885937333106995),
 ('tweets', 0.8878158330917358),
 ('tl', 0.8778461217880249),
 ('link', 0.8778210878372192),
 ('internet', 0.8753897547721863)]

In [26]:
glove_vectors1['facebook']

array([ 1.8545e+00,  7.8600e-04,  3.3901e-01, -3.0362e-01,  1.1392e+00,
       -3.0400e-01,  5.3234e-02,  8.4017e-01, -2.6918e-01,  1.2832e-01,
        1.6850e-01, -1.1183e+00, -3.5827e+00, -1.1707e+00, -1.5102e-01,
        7.2618e-01, -2.6316e-02,  1.1115e-01, -9.0396e-01, -8.3639e-01,
        3.0915e-01, -1.4184e+00, -4.6751e-01, -3.2155e-01, -6.3986e-01],
      dtype=float32)

In [27]:
glove_vectors1['twitter']

array([ 1.6952  ,  0.42694 ,  0.14433 , -0.16535 ,  1.0463  , -0.029846,
        0.33623 ,  1.5362  , -0.58481 ,  0.50349 , -0.50595 , -0.91136 ,
       -3.8011  , -0.8685  , -0.13552 ,  0.97055 , -0.13545 , -0.29825 ,
       -1.2837  , -0.63245 ,  0.44748 , -0.92231 , -0.4138  ,  0.20287 ,
       -0.33432 ], dtype=float32)

In [37]:
glove_vectors1.most_similar('mortgage')

[('payroll', 0.9481600522994995),
 ('consolidation', 0.9327718019485474),
 ('loans', 0.9307541251182556),
 ('insurance', 0.9218475818634033),
 ('loan', 0.9089252352714539),
 ('payments', 0.907196581363678),
 ('equity', 0.9053364992141724),
 ('financing', 0.9047048091888428),
 ('lenders', 0.901203453540802),
 ('tax', 0.8863474130630493)]

In [42]:
glove_vectors1.similarity('vacation', 'medication')

0.5302596

In [35]:
glove_vectors1['own']

array([ 0.12611 ,  0.26458 ,  0.058014,  0.88067 ,  0.58513 , -0.13161 ,
        0.97776 , -0.69181 ,  0.2479  , -0.26336 , -0.72009 , -0.38194 ,
       -5.1688  , -0.32566 , -0.49542 , -0.2046  ,  0.087902, -0.237   ,
        0.16039 , -0.26497 , -0.4517  ,  0.34482 , -0.070953, -0.088521,
       -0.8104  ], dtype=float32)